// <auto-generated />
using System;
using ApiCep.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiCep.Migrations
{
    [DbContext(typeof(ApiCepContext))]
    [Migration("20190604143129_CreateTable")]
    partial class CreateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiCep.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasColumnName("complemento");

                    b.Property<string>("Gia")
                        .HasColumnName("gia");

                    b.Property<string>("Ibge")
                        .HasColumnName("ibge");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnName("localidade");

                    b.Property<string>("Logradouro")
                        .HasColumnName("logradouro");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnName("uf");

                    b.Property<string>("Unidade")
                        .HasColumnName("unidade");

                    b.Property<DateTime>("ValidadeConsulta")
                        .HasColumnName("validade_consulta");

                    b.HasKey("Id");

                    b.ToTable("cep");
                });
#pragma warning restore 612, 618
        }
    }
}
